name: Run bot
on:
  schedule:
    - cron: '39 11 * * *'
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # 
      with :
          python-version: '3.10.2'
    - name: Install dependencies
      run: |
        pip install tweepy
    - name: run the bot
      run: |
        python main.py
      env:
         api_key : ${{ secrets.api_key }}
         api_secret : ${{ secrets.api_secret }}
         bearer_token : ${{ secrets.bearer_token }}
         access_token : ${{ secrets.access_token }}
         access_token_secret : ${{ secrets.access_token_secret }}
