name: Run bot
on:
  schedule:
    - cron: '33 12 * * *'
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # 
      with :
          python-version: '3.10.2'
    - name: Install dependencies
      run: |
        pip install tweepy
    - name: run the bot
      run: |
        python main.py
      env:
        PUSHPA_API_KEY : ${{ secrets.PUSHPA_API_KEY }}
        PUSHPA_API_SECRET : ${{ secrets.PUSHPA_API_SECRET }}
        PUSHPA_ACCESS_KEY : ${{ secrets.PUSHPA_ACCESS_KEY }}
        PUSHPA_ACCESS_TOKEN_SECRET : ${{ secrets.PUSHPA_ACCESS_TOKEN_SECRET }}
